# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GameEngine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GraphADT
pod 'PhysicEngine', :git => 'https://limtaeu@bitbucket.org/cs3217/2017-ps5-a0126356e.git', :branch => 'pod'

  #target 'GameEngine' do
   # inherit! :search_paths
    # Pods for testing
  #end

end
